CREATE TABLE IF NOT EXISTS cars (
	id VARCHAR(255) PRIMARY KEY,
	reg_number VARCHAR(255) NOT NULL UNIQUE,
	mark VARCHAR(255) NOT NULL,
	model VARCHAR(255) NOT NULL,
	year INT NOT NULL,
	owner VARCHAR(255) NOT NULL,
	FOREIGN KEY (owner) REFERENCES person(id)
);
